BaSP-MR-09-32: Member post
BaSP-m2023/nico-megarocket-server pull request #15
Opened 2023-05-14 00:43 UTC by EmaBaldor

Added routes controllers and validations for post

2023-05-15 20:37 UTC, JuanMornik approved these changes

2023-05-15 22:32 UTC, NicoCagnina approved these changes

2023-05-15 23:14 UTC, JuanMornik requested changes
The code in the PR name is wrong. The correct code is 32

2023-05-16 00:02 UTC, NicoCagnina requested changes

2023-05-16 00:02 UTC, NicoCagnina commented on src/validations/members.js
> +    is_active: Joi.boolean().required(),
remember to use camelCase in complex words.

2023-05-16 00:02 UTC, NicoCagnina commented on src/validations/members.js
> +    postal_code: Joi.string().min(4).max(5).required()
remember to use camelCase in complex words.

2023-05-16 02:51 UTC, NicoCagnina requested changes

2023-05-16 02:51 UTC, NicoCagnina commented on src/routes/trainer.js
> +// const validateUpdate = require('../validations/trainer');
remove this comment

2023-05-16 02:51 UTC, NicoCagnina commented on src/routes/index.js
> +// router.use('/trainer', trainerRoutes);
remove this comment

2023-05-16 02:51 UTC, NicoCagnina commented on src/routes/index.js
> +// const trainerRoutes = require('./trainer');
remove this comment

2023-05-16 03:06 UTC, NicoCagnina requested changes

2023-05-16 03:06 UTC, NicoCagnina commented on src/controllers/member.js
> +    firstName,
this name should use camelCase

2023-05-16 03:06 UTC, NicoCagnina commented on src/controllers/member.js
> +    postalCode,
this should be status code 404

2023-05-16 03:07 UTC, NicoCagnina approved these changes
Looks good to me!

2023-05-16 14:51 UTC, JuanMornik approved these changes

2023-05-16 15:06 UTC, merged