BaSP-MR-09-14: Get and get by id members
BaSP-m2023/nico-megarocket-server pull request #16
Opened 2023-05-14 17:08 UTC by EmaBaldor

Added get and get by id methods.

2023-05-15 18:20 UTC, JuanMornik approved these changes

2023-05-16 19:42 UTC, JuanMornik requested changes

2023-05-16 19:42 UTC, JuanMornik commented on src/controllers/member.js
> +    .then((member) => res.status(200).json({
- Inside .then you should add an if else for when the user is not found
- .catch missing (status 500)

2023-05-16 20:37 UTC, JuanMornik approved these changes

2023-05-16 20:44 UTC, NicoCagnina approved these changes

2023-05-16 20:55 UTC, merged