BaSP-MR-09-12: AdminUpdate
BaSP-m2023/nico-megarocket-server pull request #29
Opened 2023-05-16 04:29 UTC by enriqueanastasini

2023-05-16 14:03 UTC, NicoCagnina commented
you should add a pr description

2023-05-16 14:05 UTC, NicoCagnina requested changes

2023-05-16 14:05 UTC, NicoCagnina commented on src/models/Admins.js
> +    minLength: 5,
i think this should be a lower value. maybe 3

2023-05-16 14:05 UTC, NicoCagnina commented on src/models/Admins.js
> +    minLength: 5,
i think this should be a lower value. maybe 3

2023-05-16 14:05 UTC, NicoCagnina commented on src/validations/admins.js
> +      .pattern(/^[^@]+@[^@]+.[a-zA-Z]{2,}$/),
you can avoid the .pattern and simply put .email()

2023-05-16 19:20 UTC, enriqueanastasini commented
The put method to update ADMIN data has been implemented, and the schema has been updated to change the ADMIN data

2023-05-16 19:51 UTC, JuanMornik requested changes

2023-05-16 19:51 UTC, JuanMornik commented on src/validations/admins.js
> +    phone: Joi.number()
Phone must be a string. Keep in mind that min() and max() value will be changed with string length (9 and 12) and you have to delete positive()

2023-05-16 19:51 UTC, JuanMornik commented on src/validations/admins.js
> +  }).min(1);
Delete this .min()

2023-05-16 21:41 UTC, JuanMornik approved these changes

2023-05-17 00:23 UTC, NicoCagnina approved these changes

2023-05-17 01:00 UTC, merged