BaSP-MR-09-23: Update Class
BaSP-m2023/nico-megarocket-server pull request #30
Opened 2023-05-16 13:34 UTC by josedaniele

The put method to update class data has been implemented, and the schema has been updated to change the trainer data from a name to an ID

2023-05-16 17:51 UTC, NicoCagnina approved these changes

2023-05-16 20:30 UTC, JuanMornik requested changes

2023-05-16 20:30 UTC, JuanMornik commented on src/validations/class.js
> +    day: Joi.string()
Day must be an enum with the days of the week.
You also have to change the message and the Class schedule

2023-05-16 20:30 UTC, JuanMornik commented on src/models/Class.js
> +    match: /^(0?[1-9]|[12][0-9]|3[01])\/(0?[1-9]|1[0-2])\/\d{4}$/,
Delete this line and update classSchema according to changes indicated on validations file

2023-05-16 21:36 UTC, JuanMornik requested changes

2023-05-16 21:36 UTC, JuanMornik commented on src/validations/class.js
> +      .valid('Monday', 'Tuesday', 'Wendesday', 'Thursaday', 'Friday', 'Saturday', 'Sunday'),
Replace Wendesday with Wednesday

2023-05-16 21:43 UTC, JuanMornik commented on src/validations/class.js
> +      .valid('Monday', 'Tuesday', 'Wendesday', 'Thursaday', 'Friday', 'Saturday', 'Sunday'),
And add a message too

2023-05-17 02:21 UTC, JuanMornik approved these changes

2023-05-17 02:21 UTC, merged