BaSP-MR-09-01: Get & Get by Id
BaSP-m2023/nico-megarocket-server pull request #31
Opened 2023-05-16 15:30 UTC by Flor-Farruggia

Request created for Super Admin:
Get: to be able to see all the super admin list.
Get by id: to be able to obtain an specific super admin.

2023-05-16 17:53 UTC, NicoCagnina requested changes

2023-05-16 17:53 UTC, NicoCagnina commented on src/controllers/super-admin.js
> +    .catch((error) => res.status(400).json({
this should be 500

2023-05-16 17:53 UTC, NicoCagnina commented on src/controllers/super-admin.js
> +    .catch((error) => res.status(404).json({
this should be 500

2023-05-16 20:55 UTC, JuanMornik requested changes

2023-05-16 20:55 UTC, JuanMornik commented on src/validations/super-admin.js
> +      .required(),
Inputs aren´t required on update validations

2023-05-16 20:55 UTC, JuanMornik commented on src/validations/super-admin.js
> +      .required()
delete this require too

2023-05-16 20:58 UTC, JuanMornik approved these changes

2023-05-17 01:59 UTC, NicoCagnina approved these changes

2023-05-17 02:03 UTC, merged