BaSP-MR-09-03: POST request for super admin
BaSP-m2023/nico-megarocket-server pull request #32
Opened 2023-05-16 15:31 UTC by santimenendez98

i created the post request for create a super admin, this is validated using joi.

2023-05-16 17:55 UTC, NicoCagnina requested changes

2023-05-16 17:55 UTC, NicoCagnina commented on src/controllers/super-admin.js
> +    .catch((error) => res.status(400).json({
this should be 500

2023-05-16 17:55 UTC, NicoCagnina commented on src/routes/super-admin.js
> +router.put('/', superAdminValidation.createSuperAdminValidation, superAdminController.createSuperAdmin);
shouldn't this be `post`?

2023-05-16 21:52 UTC, JuanMornik requested changes

2023-05-16 21:52 UTC, JuanMornik commented on src/models/Super-admin.js
> +module.exports = mongoose.model('Super-admin', superAdminsSchema);
- the correct param name in mongoose model is 'Super-Admin'
- Rename the file using PascalCase

2023-05-17 00:19 UTC, JuanMornik approved these changes

2023-05-17 00:23 UTC, NicoCagnina approved these changes

2023-05-17 01:21 UTC, merged