BaSP-MR-09-27: Subscription Update.
BaSP-m2023/nico-megarocket-server pull request #34
Opened 2023-05-16 18:04 UTC by octavi01

2023-05-16 22:01 UTC, JuanMornik requested changes

2023-05-16 22:01 UTC, JuanMornik commented on src/validations/subscription.js
> +      .max('now'),
delete this validation. The user may submit suscriptions with a date after today

2023-05-16 22:11 UTC, NicoCagnina approved these changes

2023-05-17 00:08 UTC, JuanMornik approved these changes

2023-05-17 00:19 UTC, merged