BaSP-MR-61: Create trainer seed
BaSP-m2023/nico-megarocket-server pull request #45
Opened 2023-05-19 15:45 UTC by santimenendez98

Trainer seed file created.

2023-05-19 16:50 UTC, danielninfi approved these changes

2023-05-19 16:55 UTC, nazarenapantanetti commented on src/seeds/trainer.js
What about "IsActive" param?

2023-05-19 18:44 UTC, danielninfi approved these changes

2023-05-19 18:59 UTC, EmaBaldor commented on src/seeds/trainer.js
> +    _id: new mongoose.Types.ObjectId('6463fc86e024c468698af1d1'),
Consider that they must contain already existing ids in the class seeds.

2023-05-21 21:18 UTC, OscarLucero requested changes

2023-05-21 21:18 UTC, OscarLucero commented on src/seeds/trainer.js
> +    dni: '89640367',
On Models/Trainer do you have dni as a number, so you should remove al the ''.

2023-05-21 22:06 UTC, NicoCagnina approved these changes

2023-05-21 23:24 UTC, OscarLucero approved these changes

2023-05-21 23:29 UTC, merged