MR-42: Update schema and validation.
BaSP-m2023/nico-megarocket-server pull request #52
Opened 2023-05-22 14:27 UTC by Flor-Farruggia

Update to schema and validation in order to populated trainers and activity in the class files.

2023-05-22 17:14 UTC, enriqueanastasini reviewed
I think that for this to be seen in the GET you have to add the populate in the controller of CLASS

2023-05-23 00:28 UTC, EmaBaldor commented on src/models/Class.js
> +    type: [Schema.Types.ObjectId],
It does not need to be in brackets, it is not an array.

2023-05-23 01:11 UTC, EmaBaldor commented on src/models/Class.js
> +    type: [Schema.Types.ObjectId],
It does not need to be in brackets. Ok for trainer which is an array, but activity is a single identifier.

2023-05-23 14:04 UTC, EmaBaldor approved these changes

2023-05-23 18:15 UTC, JuanMornik requested changes

2023-05-23 18:15 UTC, JuanMornik commented on src/models/Class.js
> +    ref: 'trainer',
ref must be 'Trainer'

2023-05-23 18:15 UTC, JuanMornik commented on src/models/Class.js
> +    ref: 'activity',
ref must be 'Activity'

2023-05-23 18:15 UTC, JuanMornik commented on src/controllers/class.js
> +    .populate('trainer')
update populate reference with 'Trainer'

2023-05-23 18:15 UTC, JuanMornik commented on src/controllers/class.js
> +    .populate('trainer')
update populate reference with 'Trainer'

2023-05-23 20:00 UTC, JuanMornik approved these changes

2023-05-23 21:06 UTC, enriqueanastasini approved these changes

2023-05-24 02:33 UTC, merged