MR-10-58: Update Subscription schema and populate of member and class
BaSP-m2023/nico-megarocket-server pull request #53
Opened 2023-05-22 14:29 UTC by enriqueanastasini

Update Subscription schema {module} and populate of member and class {controller}

2023-05-22 15:51 UTC, EmaBaldor approved these changes

2023-05-22 15:55 UTC, Flor-Farruggia reviewed
i'm not sure, but maybe you gona need to put this info from models/Subscription.js like an array [ Schema.Types.ObjectId] but you should consult with the tutors because i'm not sure

2023-05-22 16:14 UTC, enriqueanastasini commented
> i'm not sure, but maybe you gona need to put this info from models/Subscription.js like an array [ Schema.Types.ObjectId] but you should consult with the tutors because i'm not sure

I think that i asked about that in the meeting. Each subscription only has one class and one member so the array is not necesarily. Maybe I'm wrong or didn't fully understand. I will wait the comments of the tutors. thx

2023-05-22 18:33 UTC, NicoCagnina approved these changes

2023-05-22 18:34 UTC, NicoCagnina requested changes

2023-05-22 18:34 UTC, NicoCagnina commented on src/models/Subscription.js
>      type: Schema.Types.ObjectId,
this should be an array

2023-05-22 20:44 UTC, enriqueanastasini commented on src/models/Subscription.js
>      type: Schema.Types.ObjectId,
Done

2023-05-22 23:53 UTC, nicolascagnina requested changes

2023-05-22 23:53 UTC, nicolascagnina commented on src/models/Subscription.js
> +    type: [Schema.Types.ObjectId],
This is not an array. Just the members entity

2023-05-23 19:01 UTC, JuanMornik requested changes

2023-05-23 19:01 UTC, JuanMornik commented on src/models/Subscription.js
>      required: true,
add a ref attribute please

2023-05-23 19:01 UTC, JuanMornik commented on src/models/Subscription.js
>      required: true,
add a ref attribute please (may match with the name in populate)

2023-05-23 23:14 UTC, JuanMornik approved these changes

2023-05-23 23:22 UTC, NicoCagnina approved these changes

2023-05-23 23:48 UTC, merged