BaSP-MR-64: Created test for delete and put request
BaSP-m2023/nico-megarocket-server pull request #54
Opened 2023-05-22 15:14 UTC by santimenendez98

Created test for delete and put request, these tests check different things about requests.

2023-05-23 00:25 UTC, josedaniele commented on src/tests/trainer.test.js
> +describe('DELETE /api/trainer/:id', () => {
the same as in the put

2023-05-23 00:25 UTC, josedaniele commented on src/tests/trainer.test.js
> +describe('PUT /api/trainer/:id', () => {
where is the case of non-existent id?

2023-05-23 02:19 UTC, josedaniele approved these changes

2023-05-23 05:40 UTC, danielninfi approved these changes
pass all tests

2023-05-23 18:23 UTC, JuanMornik requested changes

2023-05-23 18:23 UTC, JuanMornik commented on src/tests/trainer.test.js
> -describe('GET /api/trainer', () => {
why did you deleted this test?

2023-05-23 23:17 UTC, JuanMornik requested changes

2023-05-23 23:17 UTC, JuanMornik commented on src/tests/trainer.test.js
> +  test('Should return if the database has no objects', async () => {
Missing status 500 test

2023-05-23 23:17 UTC, JuanMornik commented on src/tests/trainer.test.js
> -describe('GET /api/trainer', () => {
I didn't see it, don't pay attention to this comment

2023-05-24 00:10 UTC, JuanMornik approved these changes

2023-05-24 00:15 UTC, merged