BaSP-MR-48: Activity test put delete
BaSP-m2023/nico-megarocket-server pull request #56
Opened 2023-05-22 18:51 UTC by nazarenapantanetti

Creation of tests to check that an activity can be updated and deleted correctly by using put/delete methods.

2023-05-22 20:53 UTC, enriqueanastasini commented on src/tests/activity.test.js
> +    expect(response.status).toBe(404);
shouldnt this be 400?

2023-05-22 20:54 UTC, enriqueanastasini commented on src/tests/activity.test.js
> +    expect(response.status).toBe(200);
and this 201?

2023-05-22 21:31 UTC, enriqueanastasini approved these changes

2023-05-22 22:12 UTC, octavi01 approved these changes

2023-05-23 05:36 UTC, danielninfi approved these changes

2023-05-23 23:22 UTC, JuanMornik requested changes

2023-05-23 23:22 UTC, JuanMornik commented on src/controllers/activity.js
> +    .catch((error) => res.status(400).json({
This must be a 500 status code.
Replace in deleteActivity function too

2023-05-24 02:26 UTC, JuanMornik approved these changes

2023-05-24 02:28 UTC, merged