BaSP-MR-37: Class tests get&post
BaSP-m2023/nico-megarocket-server pull request #63
Opened 2023-05-23 15:41 UTC by Flor-Farruggia

Create the test for the class entity for the Get, Get by Id and the post

2023-05-23 19:29 UTC, octavi01 approved these changes

2023-05-23 23:39 UTC, JuanMornik requested changes

2023-05-23 23:39 UTC, JuanMornik commented on src/models/Class.js
> +    ref: 'trainer',
Replace this with 'Trainer' to avoid conflicts in a future

2023-05-23 23:39 UTC, JuanMornik commented on src/tests/class.test.js
> +  test('This should return status 200', async () => {
Status 500 test missing

2023-05-23 23:39 UTC, JuanMornik commented on src/tests/class.test.js
> +describe('GET BY ID /api/class/:id', () => {
Status 500 test missing

2023-05-23 23:39 UTC, JuanMornik commented on src/tests/class.test.js
> +describe('POST /api/class', () => {
Status 500 test missing

2023-05-24 03:37 UTC, JuanMornik requested changes

2023-05-24 03:37 UTC, JuanMornik commented on src/tests/class.test.js
> +describe('GET BY ID /api/class/:id', () => {
valid ID test

2023-05-24 03:54 UTC, JuanMornik approved these changes

2023-05-24 03:55 UTC, merged