BaSP-MR-39: Class tests Put&Delete
BaSP-m2023/nico-megarocket-server pull request #64
Opened 2023-05-23 17:39 UTC by Flor-Farruggia

Add test for put and delete from class entity.

2023-05-23 18:05 UTC, octavi01 commented on src/tests/class.test.js
> +    expect(response.status).toBe(500);
This should be a status 400

2023-05-23 19:41 UTC, octavi01 approved these changes

2023-05-23 22:59 UTC, OscarLucero approved these changes

2023-05-23 23:41 UTC, JuanMornik requested changes

2023-05-23 23:41 UTC, JuanMornik commented on src/tests/class.test.js
> +describe('PUT /api/class/:id', () => {
Missing status 500 test

2023-05-23 23:41 UTC, JuanMornik commented on src/tests/class.test.js
> +describe('GET /api/class', () => {
Missing status 500 test

2023-05-24 03:39 UTC, JuanMornik requested changes

2023-05-24 03:39 UTC, JuanMornik commented on src/tests/class.test.js
> +describe('PUT /api/class/:id', () => {
Missing invalid ID test

2023-05-24 03:39 UTC, JuanMornik commented on src/tests/class.test.js
> +describe('DELETE /api/class/:id', () => {
Missing invalid ID test

2023-05-24 20:18 UTC, JuanMornik requested changes

2023-05-24 20:18 UTC, JuanMornik commented on src/tests/class.test.js
> +  test('Invalid id. 404 error, id not found.', async () => {
You have this test twice

2023-05-24 20:18 UTC, JuanMornik commented on src/tests/class.test.js
> +  test('Invalid route. 404 wrong route.', async () => {
Delete this test too

2023-05-24 20:18 UTC, JuanMornik commented on src/tests/class.test.js
> +  test('Server error. 500, internal server error', async () => {
Delete this test

2023-05-24 20:23 UTC, JuanMornik approved these changes

2023-05-24 20:26 UTC, merged