BaSP-MR-281: members-model
BaSP-m2023/nico-megarocket-server pull request #85
Opened 2023-06-28 22:19 UTC by Ginoboca1

- Deleted isActive from the members model
- Deleted isActive JOI validation

2023-06-28 22:53 UTC, FrancoLelli approved these changes

2023-06-28 23:17 UTC, maurojjzz approved these changes

2023-06-28 23:26 UTC, FrancoLelli requested changes
Add isActive again!

2023-06-29 00:57 UTC, FrancoLelli approved these changes

2023-06-29 15:22 UTC, merged